### ISSUE TITLE
ptol/oczor Gitter room

### ISSUE THREAD

**Issue by nponeccop** [ptol/oczor#12]
For some reason I can't do it:

- Login to http://gitter.im with GitHub account of `ptol`
- click `Add room` at the bottom
- create `ptol/oczor`

The room allows us to easily see all changes in issues and have a public discussion room

**Comment by ptol** [comment]
I have created something https://gitter.im/oczor/

**Comment by nponeccop** [comment]
It's called `community`. We need `room` which is created by `Add a Room` at the bottom of left pane.

You probably clicked `+` in the same area and created a community instead. The interface of gitter is very confusing and I even sent them a report. Look for `ADD A ROOM` button in all caps. It's big and always visible, but it's somehow hard to notice.

**Comment by ptol** [comment]
https://gitter.im/oczor/main

**Comment by nponeccop** [comment]
can you choose `ptol` as `community` during room addition, and `oczor` as `room name`? It has an advantage that all github integrations are immediately set up so we can see for example issue edits at the left pane. With current setup integrations seem to require separate steps.

If you prefer not to create `ptol/oczor` for some reason it's ok but if you don't mind then it's better.

**Comment by ptol** [comment]
https://gitter.im/ptol/oczor

**Comment by nponeccop** [comment]
Отлично
