### ISSUE TITLE
Enable Travis integration in GitHub

### ISSUE THREAD

**Issue by nponeccop** [ptol/oczor#17]
To get started with Travis CI:
- Sign in to Travis CI with your GitHub account, accepting the GitHub access permissions confirmation. 
- Once you’re signed in, and we’ve synchronized your repositories from GitHub, go to your profile page and enable Travis CI for the repository you want to build. 

Скорее всего просто можно зайти на https://travis-ci.org/ptol/oczor и там будет кнопка "включить".

`.travis.yml` я уже добавил. Если билд будет запускаться но пойдут ошибки чинить буду уже я.

**Comment by ptol** [comment]
done

**Comment by nponeccop** [comment]
Works for me. The build is green 👍
