### ISSUE TITLE
Array syntax

### ISSUE THREAD

**Issue by AnthonyJacob** [ptol/oczor#2]
I would really love to see matlab syntax for arrays:

`[9, 8, 7, 6]` is 4x1 array
`[2 4 6 8 0 2]`  is 1x6 array
`[1 2 3,4 5 6]` is 2x3 array (2 rows, 3 columns)

**Comment by AnthonyJacob** [comment]
When we combine this with oczor indent sensitivity, we get a really cool way to construct arrays:

      matrix2D :  Matrix [7, 10] Int
      matrix2D =
           44   111   89    71   60  -111   -36   116    9    56
          118  -101   56    -7   -5   127    80   -41   43   -91
          -76   104   10   -21   -4    58    -1    -8   13   116
          -39   108   75  -116  -76   -14  -103    -7   21  -126
          -29   -49   40     4  -21   -22     8    86  119   -35
           59    40   63   -99  -62    49   -80     6   44   -14
            1   -14  123    26  -31   -90   100    85    6    82

**Comment by ptol** [comment]
Wouldn't it be easier to just use something like multi-line strings?
```
 matrix2D = matrix """
       44   111   89    71   60  -111   -36   116    9    56
      118  -101   56    -7   -5   127    80   -41   43   -91
      -76   104   10   -21   -4    58    -1    -8   13   116
      -39   108   75  -116  -76   -14  -103    -7   21  -126
      -29   -49   40     4  -21   -22     8    86  119   -35
       59    40   63   -99  -62    49   -80     6   44   -14
        1   -14  123    26  -31   -90   100    85    6    82
"""
```
In this case it's possible to support any syntax you want.

**Comment by AnthonyJacob** [comment]
The reason matlab, julia, etc. adopted this array construction **is not** because they can use the syntax I presented in 2nd post.
The reason they use it is that reflects exactly how you are used to manipulate matrices in linear algebra:

1. `Vector n` is just an alias for `Matrix [n, 1]` in math. For example if they write `[1,2,3]` they expect it to be `Matrix [3, 1]`.
2. Dividing a matrix into submatrices is **very** common. For example in `A = [A1 A2 A3]` is A an `Matrix [n, a+b+c]` where `A1 : Matrix [n, a]`, `A2 : Matrix [n, b]`, `A3 : Matrix [n, c]`.

Mathematicians know exactly what this syntax means, because they use it everyday. And mathematicians usually occur in very popular topics like big data and machine learning!
