### ISSUE TITLE
Fractal syntax reinvention

### ISSUE THREAD

**Issue by hengestone** [ptol/oczor#9]
Firstly, I've been looking for something like oczor for a long time, and I would love to use it anywhere I can :)
The ability to compile to both lua and javascript is great as those are the two languages I'm using the most. There are many ML-like languages that transpile to javascript, but they all tend to be very large (F#, OCaml/Reason come to mind, but also Elm and the more Haskell-like Purescript)

Since even these large 'popular' functional languages are somewhat esoteric in their market share, inventing a syntax that's just slightly different than these strikes me as a missed opportunity.

E.g. pattern matching from https://facebook.github.io/reason/#diving-deeper-expressive-pattern-matching
type car = {maker: string, model: string};
type carList =
  | List car carList
  | NoMore;

And for oczor
x = 1
foo = case
  1 => 2
  (x,2) => 3
  (foo = x, bar = 3) => 4
  ^x => 5

Seems like using the | CASE RESULT vs CASE => RESULT is a syntactical difference only?

Would it be possible to convince you to adapt the syntax to be closer to an existing language? I know this is probably a passion project done at the end of a long work day and over weekends, but to me it seems to have real potential to become useful for a wider community, at the expense of becoming *slightly* less esoteric :)

**Comment by ptol** [comment]
>Seems like using the | CASE RESULT vs CASE => RESULT is a syntactical difference only?

I am not sure what you mean.
Do you want to replace
```
foo = case
  1 => 2
  (x,2) => 3
```
with
```
foo = case
  | 1 => 2
  | (x,2) => 3
```
?

**Comment by hengestone** [comment]
Maybe. I'm saying that for the syntax of the language as a whole it's
worthwhile using a subset of an existing language syntax where it makes
sense rather than using something unique but only slightly different.

**Comment by ptol** [comment]
I understand the idea. 
But case syntax is from Haskell
```
foo = \case
  1 -> 2
  (x,2) -> 3
```
Oczor uses different features from different languages, so there isn't any syntax subset from one language that can be used.

**Comment by hengestone** [comment]
Thanks, I understand​. Good luck!
